# coding: utf-8

"""
    Code Review API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from reviewagent_client.models.score_card import ScoreCard

class TestScoreCard(unittest.TestCase):
    """ScoreCard unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScoreCard:
        """Test ScoreCard
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScoreCard`
        """
        model = ScoreCard()
        if include_optional:
            return ScoreCard(
                problem_solving_creativity = reviewagent_client.models.score_card_item.ScoreCardItem(
                    score = 1.0, 
                    label = '', 
                    explanation = '', ),
                logic_traceability = reviewagent_client.models.score_card_item.ScoreCardItem(
                    score = 1.0, 
                    label = '', 
                    explanation = '', ),
                generalization_score = reviewagent_client.models.score_card_item.ScoreCardItem(
                    score = 1.0, 
                    label = '', 
                    explanation = '', ),
                construct_appropriateness = reviewagent_client.models.score_card_item.ScoreCardItem(
                    score = 1.0, 
                    label = '', 
                    explanation = '', ),
                self_correction_path = reviewagent_client.models.score_card_item.ScoreCardItem(
                    score = 1.0, 
                    label = '', 
                    explanation = '', ),
                variable_understanding = reviewagent_client.models.score_card_item.ScoreCardItem(
                    score = 1.0, 
                    label = '', 
                    explanation = '', ),
                control_flow_understanding = reviewagent_client.models.score_card_item.ScoreCardItem(
                    score = 1.0, 
                    label = '', 
                    explanation = '', ),
                input_output_awareness = reviewagent_client.models.score_card_item.ScoreCardItem(
                    score = 1.0, 
                    label = '', 
                    explanation = '', ),
                edge_case_awareness = reviewagent_client.models.score_card_item.ScoreCardItem(
                    score = 1.0, 
                    label = '', 
                    explanation = '', ),
                debugging_readiness = reviewagent_client.models.score_card_item.ScoreCardItem(
                    score = 1.0, 
                    label = '', 
                    explanation = '', )
            )
        else:
            return ScoreCard(
                problem_solving_creativity = reviewagent_client.models.score_card_item.ScoreCardItem(
                    score = 1.0, 
                    label = '', 
                    explanation = '', ),
                logic_traceability = reviewagent_client.models.score_card_item.ScoreCardItem(
                    score = 1.0, 
                    label = '', 
                    explanation = '', ),
                generalization_score = reviewagent_client.models.score_card_item.ScoreCardItem(
                    score = 1.0, 
                    label = '', 
                    explanation = '', ),
                construct_appropriateness = reviewagent_client.models.score_card_item.ScoreCardItem(
                    score = 1.0, 
                    label = '', 
                    explanation = '', ),
                self_correction_path = reviewagent_client.models.score_card_item.ScoreCardItem(
                    score = 1.0, 
                    label = '', 
                    explanation = '', ),
                variable_understanding = reviewagent_client.models.score_card_item.ScoreCardItem(
                    score = 1.0, 
                    label = '', 
                    explanation = '', ),
                control_flow_understanding = reviewagent_client.models.score_card_item.ScoreCardItem(
                    score = 1.0, 
                    label = '', 
                    explanation = '', ),
                input_output_awareness = reviewagent_client.models.score_card_item.ScoreCardItem(
                    score = 1.0, 
                    label = '', 
                    explanation = '', ),
                edge_case_awareness = reviewagent_client.models.score_card_item.ScoreCardItem(
                    score = 1.0, 
                    label = '', 
                    explanation = '', ),
                debugging_readiness = reviewagent_client.models.score_card_item.ScoreCardItem(
                    score = 1.0, 
                    label = '', 
                    explanation = '', ),
        )
        """

    def testScoreCard(self):
        """Test ScoreCard"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
