apiVersion: v1
kind: Secret
metadata:
  name: review-code-secret
  namespace: review-code-app
type: Opaque
stringData:
  DATABASE_USERNAME: "replace-me"
  DATABASE_PASSWORD: "replace-me"
  CLIENT_ID: "replace-me"
  CLIENT_SECRET: "replace-me"
  GOOGLE_REDIRECT_URI: "https://bbc-lms.online/api/login/oauth2/code/google"
  MINIO_ACCESS_KEY: "replace-me"
  MINIO_SECRET_KEY: "replace-me"
  FIREWORKS_API_KEY: "replace-me"
  NEO4J_USERNAME: "replace-me"
  NEO4J_PASSWORD: "replace-me"
  QDRANT_API_KEY: "replace-me"

